// Datos del colectivo Punto de Fuga

window.PDF_DATA = {
  hero: {
    tag: "Danza aérea con arneses + acciones artísticas",
    caption: "Creación y exploración de poéticas corporales",
  },

  manifiesto: {
    parrafos: [
      "Fusionamos la danza aérea con arnés y las artes escénicas para crear intervenciones, performances y obras tanto en salas y espacios convencionales como en el espacio público.",
      "Somos un colectivo artístico que surge en 2022 a partir de la convergencia de intereses, preguntas y procesos de investigación en torno a la creación escénica contemporánea.",
      "A partir de la creación de poéticas corporales en juego con la luz, el espacio, y la gravedad- en diálogo constante con el lenguaje audiovisual y el paisaje sonoro- desarrollamos propuestas que dialogan con cada entorno, generando experiencias sensibles e innovadoras que favorecen el encuentro con nuevos públicos.",
    ],
    dossierUrl: "assets/dossier colectivo_2026-.pdf",
    dossierNombre: "dossier-colectivo-2026.pdf",
    imagen: "assets/abrazo.jpg",
  },

  somos: {
    seccion: "El colectivo",
    titulo: "somos.",
    intro: "Dentro del colectivo coexisten diversidad de disciplinas y formaciones que aportan desde la singularidad de cada una, colaborando en el entramado y la potencia de la grupalidad. La identidad y sus múltiples intersecciones es un tema que nos atraviesa y que decidimos poner en juego a la hora de la creación",
    integrantes: [
      { nombre: "Elisa Acosta", fotos: ["assets/somos/Eli.jpg", "assets/somos/Eli-2.jpg", "assets/somos/Eli-3.JPG", "assets/somos/Eli-4.jpg"], bio: "Dedicada a la primera infancia, Licenciada en Psicomotricidad e instructora de yoga para niñes. Su recorrido profesional y artístico está atravesado por el movimiento, la expresión y la exploración sensible del cuerpo. Inició su camino en la gimnasia olímpica, continuó explorando el universo aéreo a través de la acrobacia en telas y, más tarde, la danza aérea con arnés, una disciplina que la cautivó por su potencia poética y creativa. Actualmente se desempeña como bailarina en el colectivo Punto de Fuga, donde continúa investigando las posibilidades del cuerpo suspendido, la relación con el espacio y la creación escénica." },
      { nombre: "Agustina Leiva", fotos: ["assets/somos/Agus-L.jpg", "assets/somos/Agus-L-2.jpg", "assets/somos/Agus-L-3.jpg"], bio: "Diseñadora, DJ y artista del movimiento. Su práctica se desarrolla a partir de una búsqueda constante en torno al cuerpo y sus posibilidades expresivas, explorando disciplinas como el yoga, el surf, la escalada, el longboard dancing, el fitness y las acrobacias aéreas. Esta diversidad de experiencias nutre una mirada sensible sobre el movimiento, la creatividad y la relación con el espacio. Actualmente integra el colectivo Punto de Fuga como bailarina aérea y creadora, investigando las posibilidades escénicas del cuerpo suspendido." },
      { nombre: "Florencia Mazzucco", fotos: ["assets/somos/Flo-2.jpg"], bio: null },
      { nombre: "Leticia Moreno Citraro", fotos: ["assets/somos/Leti.jpg", "assets/somos/Leti-2.jpg", "assets/somos/Leti-3.JPG"], bio: "Arquitecta, con una práctica que explora los vínculos entre arquitectura, naturaleza y paisaje de una forma sensible y consciente. Con una formación permanente y continua en diferentes disciplinas artísticas tanto plásticas como del movimiento, encuentra en la danza aérea un lenguaje capaz de articular y potenciar los múltiples intereses formativos, vinculando el cuerpo, el espacio, el movimiento y la percepción, destacando su potencia expresiva para comunicar ideas y explorar nuevos sentidos, siendo un vector creativo personal fundamental. Participó como co-creadora e intérprete de danza aérea en Guarecerse (2024), una experiencia multisensorial en un sendero natural, obra desarrollada en Villa Serrana con apoyo del MEC. Desde el 2024 integra el Colectivo Punto de Fuga, participando como co-creadora y bailarina aérea." },
      { nombre: "Anaclara Oyenart", fotos: ["assets/somos/Anaclara.jpg", "assets/somos/Anaclara-2.jpg", "assets/somos/Anaclara-3.jpg", "assets/somos/Anaclara-4.JPG", "assets/somos/Anaclara-5.jpg"], bio: "Licenciada en Diseño de Comunicación Visual y artista escénica con trayectoria en danza aérea con arnés. Forma parte de Punto de Fuga desde sus inicios, donde confluyen su práctica escénica y su trabajo como diseñadora — responsable de la identidad visual del colectivo. Con más de 15 años de formación continua en disciplinas aéreas y circenses, desarrolla proyectos en el cruce entre diseño, gestión cultural y escena." },
      { nombre: "Stella Peña", fotos: ["assets/somos/stella.jpg", "assets/somos/stella-2.jpg", "assets/somos/stella-3.jpg", "assets/somos/stella-4.jpg", "assets/somos/stella-5.jpg"], bio: "Bailarina, acróbata, aerealista y química. Realizó un doctorado en Química donde la mayor parte del tiempo estaba creando y sintetizando compuestos químicos bioactivos. Por lo que la experimentación y la investigación atraviesan sus poros tanto a nivel científico como a través del movimiento y la fusión de danza contemporánea y circo. Es directora de la obra PLASTIKUS, ha integrado diversos colectivos de danza y circo como Prácticas Bestiales, Proyecto Incorporar, ENTRE, Fúa, La Masa, Invertidos Circo. Actualmente es bailarina aérea y creadora en el Colectivo Punto de Fuga. Cuenta con más de 18 años de experiencia docente en acrobacias aéreas, donde desarrolla una pedagogía integral enfocada en el desarrollo humano." },
      { nombre: "Agustina Rodríguez", bio: null },
      { nombre: "Diego Ruella", fotos: ["assets/somos/diego.jpg", "assets/somos/Diego-2.JPG", "assets/somos/Diego-3.JPG"], bio: "Artista escénico, coreógrafo y docente. Formado en Fotografía (Udelar), Docencia en Danza (IPA) y Danza Contemporánea (SODRE), complementa su trayectoria con estudios en acrobacia y danza aérea con arneses. Integra la Red de Artes Circenses del Uruguay (RACU) y el colectivo Punto de Fuga. Ha participado en producciones junto a La Fura dels Baus y en obras de danza contemporánea como Suite Gardel, Transparente y EX-ES, entre otras. Es co-creador de Buscar Nada en Ti y R.O.J.O. (Premio Jóvenes Creadores). Dirige y produce proyectos de danza contemporánea y danza aérea con arneses." },
    ],
  },

  cuerpo: {
    titulo: "Metodología de creación\ndel cuerpo al texto, y del texto al cuerpo",
    parrafos: [
      "Trabajamos a partir de improvisaciones y estructuras compositivas que guían la creación.",
      "Concebimos la obra como organismo vivo.",
      "La danza aérea con arnés nos permite desafiar la gravedad y expandir las posibilidades de movimiento en diálogo con el espacio y el equilibrio",
    ],
  },

  accionesMeta: {
    num: "Acciones artísticas",
    titulo: "| obras | performances | intervenciones |",
  },

  acciones: [
    {
      slug: "tramas-colectivas",
      year: "2026",
      title: "Tramas Colectivas",
      sub: "Proyecto Fortalecimiento de las Artes",
      tipo: "Proyecto",
      lugar: "Plaza Liber seregni / Espacio modelo / Balcón del Cerro / Plaza Feminnista Las Pioneras",
      destacado: true,
      imagen: "assets/acciones/tramas-colectivas/portada.jpg",
      descripcion: "Tramas Colectivas es un proyecto de fortalecimiento de las artes escénicas que busca tejer redes entre creadoras, espacios y comunidades. Una apuesta colectiva por la sostenibilidad de las prácticas artísticas independientes en Uruguay.",
      galeria: [
        { seccion: "Plaza Liber Seregni", fotos: [] },
        { seccion: "Espacio Modelo", fotos: [] },
        { seccion: "Balcón del Cerro", fotos: Array.from({ length: 23 }, (_, i) => `assets/acciones/tramas-colectivas/balcon-del-cerro/balcon_img-${i + 1}.jpg`) },
        { seccion: "Plaza Feminista Las Pioneras", fotos: [] },
      ],
    },
    {
      slug: "fugas-al-este",
      year: "2026",
      title: "Fugas al Este",
      sub: "Intervención",
      tipo: "Intervención",
      lugar: "Grutas de Punta Ballena - Bosque y arroyo",
      imagen: "assets/acciones/fugas-al-este/fugas-al-este_img-1.jpg",
      descripcion: "Una intervención de danza aérea con arnés en los paisajes naturales de la costa este uruguaya. Cuerpos suspendidos entre el bosque, el arroyo y las grutas de Punta Ballena, en un diálogo entre gravedad, naturaleza y movimiento.",
      ficha: {
        cocreacion: "Punto de Fuga",
        elenco: ["Anaclara Oyenart", "Florencia Mazzucco", "Elisa Acosta", "Agustina Leiva", "Stella Peña", "Leticia Moreno"],
        produccion: "Punto de Fuga",
        vestuario: "Punto de Fuga",
        registro: "Leticia Moreno, Diego Ruella",
        realizacion: "Febrero 2026",
      },
      galeria: [
        { seccion: "Bosque y Arroyo", fotos: [] },
        { seccion: "Grutas y Punta Ballena", fotos: [] },
      ],
    },
    {
      slug: "capas",
      year: "2025",
      title: "Capas",
      sub: "Performance multidisciplinaria",
      tipo: "Performance",
      lugar: "Espacio MUMI · Noche de los Museos",
      imagen: "assets/acciones/capas/mumi.jpg",
      descripcion: "Performance multidisciplinaria presentada en la Noche de los Museos en el Espacio MUMI. Una exploración de las capas del cuerpo en movimiento — lo visible y lo invisible, lo que se muestra y lo que se oculta — a través de la danza aérea y las artes escénicas.",
      galeria: [{ seccion: "Registro", fotos: Array.from({ length: 10 }, (_, i) => `assets/acciones/capas/capas_img-${i + 1}.jpg`) }],
      graficas: [
        "assets/acciones/capas/graficas/capas_flyer-mumi.jpg",
        "assets/acciones/capas/graficas/capas_story-hoy.jpg",
        "assets/acciones/capas/graficas/capas_posteo-3a.jpg",
        "assets/acciones/capas/graficas/capas_posteo-3b.jpg",
        "assets/acciones/capas/graficas/capas_posteo-4.jpg",
        "assets/acciones/capas/graficas/capas_posteo-5.jpg",
        "assets/acciones/capas/graficas/capas_posteo-6.jpg",
      ],
      videos: [
        { label: "Spot", src: "assets/acciones/capas/graficas/capas_spot-1.mp4" },
        { label: "Video", src: "assets/acciones/capas/graficas/capas_video-1.mp4" },
      ],
    },
    {
      slug: "artivismo-por-palestina",
      year: "2025",
      title: "Artivismo por Palestina",
      sub: "Activación escénica · Varieté Artivismo · Colaboración del colectivo LAS SELVAS",
      tipo: "Intervención",
      lugar: "Plaza Liber Seregni",
      imagen: "assets/acciones/artivismo-por-palestina/portada.jpg",
      descripcion: "Activación escénica realizada en el marco del Varieté Artivismo por Palestina en la Plaza Liber Seregni. La propuesta explora el potencial del cuerpo como dispositivo poético y político, generando una acción situada que pone en diálogo movimiento, espacio público y compromiso social.",
      ficha: {
        direccion: "Diego Ruella",
        cocreacion: "Punto de Fuga",
        colaboracion: "Las Selvas",
        elenco: ["Anaclara Oyenart", "Florencia Mazzucco", "Elisa Acosta", "Agustina Leiva", "Stella Peña", "Leticia Moreno"],
        produccion: "Cirqueras Feministas",
        vestuario: "Punto de Fuga",
        duracion: "20 minutos",
      },
    },
    {
      slug: "espacio-bahia",
      year: "2025",
      title: "Espacio Bahía",
      sub: "Performance",
      tipo: "Performance",
      lugar: "Espacio Bahía",
      imagen: "assets/acciones/espacio-bahia/portada.jpg",
      descripcion: "Performance presentada en Espacio Bahía, un encuentro entre el cuerpo suspendido y la arquitectura del lugar. La danza aérea con arnés como lenguaje que habita y transforma los espacios.",
      galeria: [{ seccion: "Registro", fotos: Array.from({ length: 26 }, (_, i) => `assets/acciones/espacio-bahia/bahia_img-${i + 1}.jpg`) }],
    },
    {
      slug: "29m-pioneras",
      year: "2025",
      title: "29M Pioneras",
      sub: "Taller gratuito + intervención artística",
      tipo: "Intervención",
      lugar: "Plaza Las Pioneras · Municipio C",
      imagen: "assets/acciones/29m-pioneras/portada.jpg",
      descripcion: "En el marco del 29 de marzo, Día Internacional de las Mujeres Trabajadoras, ofrecimos un taller gratuito de danza aérea abierto a la comunidad, seguido de una intervención artística en la Plaza Las Pioneras. Arte, cuerpo y feminismo en el espacio público.",
      galeria: [
        { seccion: "Taller", fotos: Array.from({ length: 19 }, (_, i) => `assets/acciones/29m-pioneras/taller/taller_img-${i + 1}.jpg`) },
        { seccion: "Intervención", fotos: ["assets/acciones/29m-pioneras/intervencion/29m-pioneras.jpg", "assets/acciones/29m-pioneras/intervencion/29m-pioneras2.jpg"] },
      ],
    },
    {
      slug: "fugas-colectivas-vol-ii",
      year: "2024",
      title: "Fugas Colectivas Vol. II",
      sub: "Obra de danza aérea en arnés",
      tipo: "Obra",
      lugar: "Sala El Picadero",
      mes: "Diciembre",
      imagen: "assets/acciones/fugas-colectivas-vol-ii/portada.jpg",
      descripcion: "Segunda edición de Fugas Colectivas en la Sala El Picadero. La obra regresa con nuevas capas de sentido, profundizando en el lenguaje del cuerpo suspendido y la poética del movimiento colectivo. Fugas Colectivas, porque el futuro será colectivo.",
      galeria: [
        {
          seccion: "Registro",
          fotos: [
            "assets/acciones/fugas-colectivas-vol-ii/A-2.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-3.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-5.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-9.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-19.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-45.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-50.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-56.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-58.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-63.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-67.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-71-2.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-74.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-77.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-105.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-117.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-124.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-130.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-141.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-142.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-146.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-152.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-160.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-168.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-177.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-191.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-196.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-197.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-201.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-207.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-218.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-221.jpg",
          ],
        },
      ],
      graficas: [
        "assets/acciones/fugas-colectivas-vol-ii/graficas/fugas_ii_afiche-dic.jpg",
        "assets/acciones/fugas-colectivas-vol-ii/graficas/fugas_ii_grafica-6.jpg",
        "assets/acciones/fugas-colectivas-vol-ii/graficas/fugas_ii_grafica-7.jpg",
        "assets/acciones/fugas-colectivas-vol-ii/graficas/fugas_ii_posteo-1a.jpg",
        "assets/acciones/fugas-colectivas-vol-ii/graficas/fugas_ii_posteo-1b.jpg",
        "assets/acciones/fugas-colectivas-vol-ii/graficas/fugas_ii_posteo-1c.jpg",
        "assets/acciones/fugas-colectivas-vol-ii/graficas/fugas_ii_posteo-3a.jpg",
        "assets/acciones/fugas-colectivas-vol-ii/graficas/fugas_ii_posteo-4a.jpg",
        "assets/acciones/fugas-colectivas-vol-ii/graficas/fugas_ii_posteo-5b.jpg",
      ],
      videos: [
        { label: "Reel", src: "assets/acciones/fugas-colectivas-vol-ii/graficas/fugas_ii_reel-1.mp4" },
        { label: "Spot lanzamiento", src: "assets/acciones/fugas-colectivas-vol-ii/graficas/fugas_ii_spot-lanzamiento.mp4" },
        { label: "Spot lanzamiento (alt)", src: "assets/acciones/fugas-colectivas-vol-ii/graficas/fugas_ii_spot-lanzamiento-2.mp4" },
        { label: "Video", src: "assets/acciones/fugas-colectivas-vol-ii/graficas/fugas_ii_video-1.mp4" },
      ],
    },
    {
      slug: "fugas-colectivas-vol-i",
      year: "2024",
      mes: "Julio",
      title: "Fugas Colectivas Vol. I",
      sub: "Obra de danza aérea en arnés",
      tipo: "Obra",
      lugar: "Sala El Picadero",
      imagen: "assets/acciones/fugas-colectivas-vol-i/portada.jpg",
      frase: "Fugas Colectivas, porque el futuro será colectivo.",
      ficha: {
        direccion: "Diego Ruella",
        cocreacion: "Punto de Fuga",
        elenco: ["Elisa Acosta", "Victoria Berreta", "Florencia Mazzucco", "Anaclara Oyenart", "Agustina Rodríguez"],
        produccion: "Punto de Fuga",
        vestuario: "Punto de Fuga",
      },
      descripcion: "Fugas Colectivas es un espectáculo que, desde el lenguaje visual-poético y las artes del movimiento, explora los vínculos y las formas en que nuestros cuerpos son afectados por enunciados hegemónicos que buscan invisibilizarnos. Interpretada por un elenco exclusivamente femenino de siete artistas, esta performance se sumerge en las múltiples posibilidades que emergen del encuentro y desencuentro entre los cuerpos en un espacio finito. La obra construye un juego espacial a través de direcciones trazadas con luces, movimientos, péndulos, espirales, desequilibrios, puntos y líneas, tejiendo una trama de interacciones y cruces que dan vida a una pintura en movimiento. Fugas Colectivas, porque el futuro será colectivo.",
      galeria: [{ seccion: "Registro", fotos: Array.from({ length: 42 }, (_, i) => `assets/acciones/fugas-colectivas-vol-i/fugas_i_img-${i + 1}.jpg`) }],
      graficas: [
        "assets/acciones/fugas-colectivas-vol-i/graficas/fugas_i_grafica-1.jpg",
        "assets/acciones/fugas-colectivas-vol-i/graficas/fugas_i_grafica-2.jpg",
        "assets/acciones/fugas-colectivas-vol-i/graficas/fugas_i_grafica-3.jpg",
        "assets/acciones/fugas-colectivas-vol-i/graficas/fugas_i_grafica-4.jpg",
        "assets/acciones/fugas-colectivas-vol-i/graficas/fugas_i_grafica-5.jpg",
      ],
      videos: [{ label: "Reel", src: "assets/acciones/fugas-colectivas-vol-i/graficas/fugas_i_reel-1.mp4" }],
    },
    {
      slug: "apertura-proceso-creativo",
      year: "2023",
      title: "Apertura de proceso creativo",
      sub: "Muestra abierta",
      tipo: "Ensayo",
      lugar: "La Galponera espacio de circo",
      imagen: "assets/acciones/apertura-proceso-creativo/portada.jpg",
      videos: [
        { label: "Video 1", src: "assets/acciones/apertura-proceso-creativo/apertura_video-1.mp4" },
        { label: "Video 2", src: "assets/acciones/apertura-proceso-creativo/apertura_video-2.mp4" },
        { label: "Video 3", src: "assets/acciones/apertura-proceso-creativo/apertura_video-3.mp4" },
        { label: "Video 4", src: "assets/acciones/apertura-proceso-creativo/apertura_video-4.mp4" },
      ],
      descripcion: "Muestra abierta del proceso creativo de Fugas Colectivas en La Galponera. Un espacio de encuentro con el público para compartir el trabajo en construcción — la obra en su estado más vivo y vulnerable.",
      galeria: [{ seccion: "Registro", fotos: Array.from({ length: 19 }, (_, i) => `assets/acciones/apertura-proceso-creativo/apertura_img-${i + 1}.jpg`) }],
    },
    {
      slug: "investigacion-visual-luces",
      year: "2022",
      title: "Investigación Visual y Luces",
      sub: "Proceso de investigación",
      tipo: "Ensayo",
      lugar: "Lugar de ensayo",
      imagen: "assets/acciones/investigacion-visual-luces/portada.jpg",
      descripcion: "Investigación de luces y visuales — exploración del espacio escénico a través de la luz y los recursos visuales como herramientas de creación.",
      galeria: [
        {
          seccion: "Registro",
          fotos: [
            "assets/acciones/investigacion-visual-luces/inv-visual_img-1.jpg",
            "assets/acciones/investigacion-visual-luces/inv-visual_img-2.jpg",
            "assets/acciones/investigacion-visual-luces/inv-visual_img-3.jpg",
            "assets/acciones/investigacion-visual-luces/inv-visual_img-4.jpg",
          ],
        },
      ],
      videos: [{ label: "Video", src: "assets/acciones/investigacion-visual-luces/inv-visual_video-1.mp4" }],
    },
  ],

  nosInteresa: [
    {
      lead: "Explorar y crear",
      cuerpo: "a través de la danza aérea en diálogo con otros lenguajes, piezas escénicas singulares con identidad propia.",
    },
    {
      lead: "Realizar intervenciones artísticas diversas",
      cuerpo: "y adaptables a múltiples espacios escénicos.",
    },
    {
      lead: "Favorecer encuentros",
      cuerpo: "a través de intervenciones en espacios abiertos a la comunidad, promoviendo el sentido de pertenencia y el uso del espacio público.",
    },
    {
      lead: "Difundir la danza aérea con arneses",
      cuerpo: "destacando su potencial para la investigación y la exploración del trabajo con el cuerpo.",
    },
  ],

  footer: {
    copyright: "© 2018–2026 · Colectivo Punto de Fuga",
  },

  contacto: {
    titulo: "Escribinos.",
    tituloEm: "Programemos.",
    email: "puntodefuga.danzaerea@gmail.com",
    instagram: "puntodefuga.danzaerea",
    instagramUrl: "https://www.instagram.com/puntodefuga.danzaerea/",
    location: "Montevideo · Uruguay",
  },
};
