// Datos del colectivo Punto de Fuga

window.PDF_DATA = {
  hero: {
    tag: "Danza aérea con arneses + acciones artísticas",
    caption: "Creación y exploración de poéticas corporales",
  },

  manifiesto: {
    parrafos: [
      "Fusionamos la danza aérea con arnés y las artes escénicas para crear intervenciones, performances y obras tanto en salas y espacios convencionales como en el espacio público.",
      "Somos un colectivo artístico que surge en 2022 a partir de la convergencia de intereses, preguntas y procesos de investigación en torno a la creación escénica contemporánea.",
      "A partir de la creación de poéticas corporales en juego con la luz, el espacio, y la gravedad- en diálogo constante con el lenguaje audiovisual y el paisaje sonoro- desarrollamos propuestas que dialogan con cada entorno, generando experiencias sensibles e innovadoras que favorecen el encuentro con nuevos públicos.",
    ],
    dossierUrl: "assets/dossier colectivo_2026-.pdf",
    dossierNombre: "dossier-colectivo-2026.pdf",
  },

  somos: {
    seccion: "El colectivo",
    titulo: "somos.",
    intro: "Dentro del colectivo coexisten diversidad de disciplinas y formaciones que aportan desde la singularidad de cada una, colaborando en el entramado y la potencia de la grupalidad. La identidad y sus múltiples intersecciones es un tema que nos atraviesa y que decidimos poner en juego a la hora de la creación",
    integrantes: [
      { nombre: "Elisa Acosta", fotos: ["assets/somos/Eli.jpg", "assets/somos/Eli-2.jpg", "assets/somos/Eli-3.JPG", "assets/somos/Eli-4.jpg"], bio: "Dedicada a la primera infancia, Licenciada en Psicomotricidad e instructora de yoga para niñes. Su recorrido profesional y artístico está atravesado por el movimiento, la expresión y la exploración sensible del cuerpo. Inició su camino en la gimnasia olímpica, continuó explorando el universo aéreo a través de la acrobacia en telas y, más tarde, la danza aérea con arnés, una disciplina que la cautivó por su potencia poética y creativa. Actualmente se desempeña como bailarina en el colectivo Punto de Fuga, donde continúa investigando las posibilidades del cuerpo suspendido, la relación con el espacio y la creación escénica." },
      { nombre: "Agustina Leiva", fotos: ["assets/somos/Agus-L.jpg", "assets/somos/Agus-L-2.jpg", "assets/somos/Agus-L-3.jpg"], bio: "Diseñadora, DJ y artista del movimiento. Su práctica se desarrolla a partir de una búsqueda constante en torno al cuerpo y sus posibilidades expresivas, explorando disciplinas como el yoga, el surf, la escalada, el longboard dancing, el fitness y las acrobacias aéreas. Esta diversidad de experiencias nutre una mirada sensible sobre el movimiento, la creatividad y la relación con el espacio. Actualmente integra el colectivo Punto de Fuga como bailarina aérea y creadora, investigando las posibilidades escénicas del cuerpo suspendido." },
      { nombre: "Florencia Mazzucco Oberti", fotos: ["assets/somos/Flo.jpg", "assets/somos/Flo-2.JPG", "assets/somos/Flo-3.jpg", "assets/somos/Flo-4.jpg"], bio: "Bailarina aérea y co-creadora del colectivo desde el 2022. Ha investigado en distintas disciplinas artísticas del circo, la danza contemporánea y danza aérea, así como también en la escritura poética. Educadora social y Educadora Sexual Integral, formaciones que articulan a la hora de la creación y composición artística desde una perspectiva social y de género. Sus prácticas se basan en la percepción del mundo, el movimiento y los vínculos como acontecimiento poético. Participó como co-creadora e intérprete de danza aérea en Guarecerse (2024), obra desarrollada en Villa Serrana con apoyo del MEC (Apoyo a propuestas artístico culturales en territorio). Participa de la creación y distintas acciones artísticas de Punto de Fuga desde sus inicios." },
      { nombre: "Leticia Moreno Citraro", fotos: ["assets/somos/Leti.jpg", "assets/somos/Leti-2.jpg", "assets/somos/Leti-3.JPG", "assets/somos/Leti-4.jpg"], bio: "Arquitecta, con una práctica que explora los vínculos entre arquitectura, naturaleza y paisaje de una forma sensible y consciente. Con una formación permanente y continua en diferentes disciplinas artísticas tanto plásticas como del movimiento, encuentra en la danza aérea un lenguaje capaz de articular y potenciar los múltiples intereses formativos, vinculando el cuerpo, el espacio, el movimiento y la percepción, destacando su potencia expresiva para comunicar ideas y explorar nuevos sentidos, siendo un vector creativo personal fundamental. Participó como co-creadora e intérprete de danza aérea en Guarecerse (2024), una experiencia multisensorial en un sendero natural, obra desarrollada en Villa Serrana con apoyo del MEC. Desde el 2024 integra el Colectivo Punto de Fuga, participando como co-creadora y bailarina aérea." },
      { nombre: "Anaclara Oyenart Cánepa", fotos: ["assets/somos/Anaclara.jpg", "assets/somos/Anaclara-2.JPG", "assets/somos/Anaclara-3.jpg", "assets/somos/Anaclara-4.jpg"], bio: "Licenciada en Diseño de Comunicación Visual y artista escénica con trayectoria en danza aérea con arnés. Forma parte de Punto de Fuga desde sus inicios, donde confluyen su práctica escénica y su trabajo como diseñadora — responsable de la identidad visual del colectivo. Con más de 15 años de formación continua en disciplinas aéreas y circenses, desarrolla proyectos en el cruce entre diseño, gestión cultural y escena. Su recorrido incluye la cogestión de espacios y proyectos culturales independientes, además de su trabajo en diseño digital desde 2014. Esa doble mirada, entre lo gráfico y lo performático, atraviesa su forma de trabajar." },
      { nombre: "Stella Peña", fotos: ["assets/somos/stella.jpg", "assets/somos/stella-2.jpg", "assets/somos/stella-3.jpg", "assets/somos/stella-4.jpg"], bio: "Bailarina, acróbata, aerealista y química. Realizó un doctorado en Química donde la mayor parte del tiempo estaba creando y sintetizando compuestos químicos bioactivos. Por lo que la experimentación y la investigación atraviesan sus poros tanto a nivel científico como a través del movimiento y la fusión de danza contemporánea y circo. Es directora de la obra PLASTIKUS, ha integrado diversos colectivos de danza y circo como Prácticas Bestiales, Proyecto Incorporar, ENTRE, Fúa, La Masa, Invertidos Circo. Actualmente es bailarina aérea y creadora en el Colectivo Punto de Fuga. Cuenta con más de 18 años de experiencia docente en acrobacias aéreas, donde desarrolla una pedagogía integral enfocada en el desarrollo humano." },
      { nombre: "Agustina Rodríguez", fotos: ["assets/somos/Agus-R.jpg", "assets/somos/Agus-R-2.jpeg", "assets/somos/Agus-R-3.jpeg", "assets/somos/Agus-R-4.jpeg"], bio: "Artista escénica de danza aérea con arnés, participando de punto de fuga desde sus inicios. Recorrió diversas disciplinas aéreas tales como la tela, el trapecio y la danza aérea con arnés desde la práctica escénica y la docencia. De formación Educadora Social, entramando pedagogía y cuerpo, y comprometida con democratizar el acceso a la cultura. Mamá desde el 2025, habitando el mundo desde un nuevo lugar." },
      { nombre: "Diego Ruella", fotos: ["assets/somos/diego.jpg", "assets/somos/Diego-2.JPG", "assets/somos/Diego-3.JPG"], bio: "Artista escénico, coreógrafo y docente. Formado en Fotografía (Udelar), Docencia en Danza (IPA) y Danza Contemporánea (SODRE), complementa su trayectoria con estudios en acrobacia y danza aérea con arneses. Integra la Red de Artes Circenses del Uruguay (RACU) y el colectivo Punto de Fuga. Ha participado en producciones junto a La Fura dels Baus y en obras de danza contemporánea como Suite Gardel, Transparente y EX-ES, entre otras. Es co-creador de Buscar Nada en Ti y R.O.J.O. (Premio Jóvenes Creadores). Dirige y produce proyectos de danza contemporánea y danza aérea con arneses." },
    ],
  },

  cuerpo: {
    titulo: "Metodología de creación\ndel cuerpo al texto, \ny del texto al cuerpo",
    parrafos: [
      "Trabajamos a partir de improvisaciones y estructuras compositivas que guían la creación.",
      "Concebimos la obra como organismo vivo.",
      "La danza aérea con arnés nos permite desafiar la gravedad y expandir las posibilidades de movimiento en diálogo con el espacio y el equilibrio",
    ],
  },

  accionesMeta: {
    num: "Acciones artísticas",
    titulo: "| obras | performances | intervenciones | exploraciones",
  },

  acciones: [
    {
      slug: "tramas-colectivas",
      year: "2026",
      title: "Tramas Colectivas",
      sub: "Proyecto Fortalecimiento de las Artes",
      tipo: "Proyecto",
      lugar: "Plaza Liber seregni / Espacio modelo / Balcón del Cerro / Plaza Feminnista Las Pioneras",
      destacado: true,
      imagen: "assets/acciones/tramas-colectivas/portada.jpg",
      descripcion: "Tramas Colectivas es un proyecto de intervención comunitaria que busca tejer redes entre creadoras, espacios y comunidades, una apuesta colectiva por la sostenibilidad de las prácticas artísticas independientes en Montevideo.<br><br>Fue premiado por el Programa Fortalecimiento de las Artes de la Intendencia de Montevideo, en la categoría Danza - proyectos especiales.<br><br>Fue desarrollado en 2026 en 4 municipios de la Ciudad de Montevideo: Espacio Modelo - municipio D, Espacio Plaza Las Pioneras - municipio C, Espacio Balcón del Cerro - municipio A y Plaza Líber Seregni - municipio B.",
      ficha: {
        direccion: "Diego Ruella",
        cocreacion: "Punto de Fuga",
        gestion: ["Agustina Leiva", "Florencia Mazzucco"],
        produccion: "Punto de Fuga",
        registro: "Reinaldo Altamirano",
        disenoGrafico: "Anaclara Oyenart",
        montaje: ["Diego Ruella", "Elisa Acosta", "Leticia Moreno", "Stella Peña"],
        realizacion: "El proyecto se desarrolló durante los meses de febrero-mayo de 2026",
      },
      galeria: [
        {
          seccion: "Plaza Liber Seregni",
          fotos: [
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-7.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-11.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-14.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-19.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-21 (1).jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-29.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-30.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-34.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-35.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-36.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-38.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-52.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-59.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-61.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-64.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-70.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-71.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-76.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-80.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-82.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-83.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-84.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-86.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-89.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-91.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-93.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-97.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-98.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-101.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-103.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-105.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-110.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-111.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-112.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-114.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-118.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-119.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-122.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-128.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-129.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-131.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-133.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-134.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-135.jpg",
            "assets/acciones/tramas-colectivas/Plaza-Liber-seregni/A-136.jpg",
          ],
        },
        {
          seccion: "Espacio Modelo",
          fotos: [
            "assets/acciones/tramas-colectivas/espacio-modelo/A-142.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-144.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-145.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-149.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-151.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-154.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-155.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-159.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-161.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-169.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-170.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-173.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-174.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-175.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-176.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-177.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-180.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-181.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-183.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-188 (2).jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-193.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-195.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-196.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-202.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-203.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-206.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-207.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-209.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-212.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-213.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-214.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-216.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-221.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-225.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-227.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-228.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-229.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-236.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-240.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-245.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-246.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-250.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-254.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-257.jpg",
            "assets/acciones/tramas-colectivas/espacio-modelo/A-267.jpg",
          ],
        },
        {
          seccion: "Balcón del Cerro",
          fotos: [
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-281.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-282.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-284.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-285.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-288.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-289.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-290.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-292.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-294.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-301.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-306.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-307 (2).jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-308.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-310.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-311.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-313.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-314.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-318.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-324.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-325.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-327.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-329.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-334.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-339.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-341.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-347.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-352.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-370.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-383.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-394.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-399.jpg",
            "assets/acciones/tramas-colectivas/balcon-del-cerro/A-406.jpg",
          ],
        },
        {
          seccion: "Plaza Feminista Las Pioneras",
          fotos: [],
        },
      ],
      graficas: [
        "assets/acciones/tramas-colectivas/graficas/tramascolectivas_full_1080x1350.jpg",
        "assets/acciones/tramas-colectivas/graficas/tramascolectivas_seregni-individual_1080x1350.png",
        "assets/acciones/tramas-colectivas/graficas/tramascolectivas_modelo-individual_1080x1350.png",
        "assets/acciones/tramas-colectivas/graficas/tramascolectivas_cerro-individual_flyer.png",
        "assets/acciones/tramas-colectivas/graficas/tramascolectivas_pioneras-individual_1080x1350.png",
      ],
    },
    {
      slug: "fugas-al-este",
      year: "2026",
      title: "Fugas al Este",
      sub: "Intervención",
      tipo: "Intervención",
      lugar: "Grutas de Punta Ballena - Bosque y arroyo",
      imagen: "assets/acciones/fugas-al-este/fugas-al-este_img-1.jpg",
      descripcion: "Una intervención de danza aérea con arnés en los paisajes naturales de la costa este uruguaya. Cuerpos suspendidos entre el bosque, el arroyo y las grutas de Punta Ballena, en un diálogo entre gravedad, naturaleza y movimiento.",
      ficha: {
        cocreacion: "Punto de Fuga",
        elenco: ["Agustina Leiva", "Anaclara Oyenart", "Diego Ruella", "Elisa Acosta", "Florencia Mazzucco", "Leticia Moreno", "Stella Peña"],
        produccion: "Punto de Fuga",
        vestuario: "Punto de Fuga",
        registro: "Leticia Moreno, Diego Ruella",
        realizacion: "Febrero 2026",
      },
      galeria: [
        {
          seccion: "Bosque y Arroyo",
          fotos: Array.from({ length: 21 }, (_, i) => `assets/acciones/fugas-al-este/bosque/bosque-${String(i + 1).padStart(2, "0")}.webp`),
        },
        {
          seccion: "Grutas y Punta Ballena",
          fotos: Array.from({ length: 22 }, (_, i) => `assets/acciones/fugas-al-este/grutas/grutas-${String(i + 1).padStart(2, "0")}.webp`),
        },
      ],
    },
    {
      slug: "capas",
      year: "2025",
      title: "Noche de los Museos _ Espacio MUMI ",
      sub: "Performance multidisciplinaria",
      tipo: "Performance",
      lugar: "Espacio MUMI · Noche de los Museos",
      imagen: "assets/acciones/capas/capas-hero.webp",
      descripcion: "Performance multidisciplinaria creada para la Noche de los Museos en el Espacio MUMI. La propuesta indaga en las capas visibles e invisibles que habitan el cuerpo en movimiento, explorando los umbrales entre presencia y ausencia, revelación y ocultamiento. A través de la danza aérea y las artes escénicas, se construye un paisaje sensible donde el cuerpo se transforma en territorio de memoria, experiencia e imaginación. En diálogo con la arquitectura del espacio, la obra resignifica recorridos, alturas y perspectivas, integrando la estructura edilicia como parte activa de la experiencia escénica.",
      ficha: {
        direccion: "Diego Ruella",
        cocreacion: "Punto de Fuga",
        elenco: ["Agustina Leiva", "Anaclara Oyenart", "Elisa Acosta", "Florencia Mazzucco", "Leticia Moreno", "Stella Peña"],
        produccion: "Punto de Fuga",
        vestuario: "Agustina Leiva",
        textos: "Florencia Mazzucco",
        luces: "Diego Ruella",
        visuales: ["Agustina Leiva", "Anaclara Oyenart"],
        audio: "Stella Peña",
        disenoGrafico: "Anaclara Oyenart",
        duracion: "30 minutos",
      },
      galeria: [
        {
          seccion: "Registro",
          fotos: Array.from({ length: 26 }, (_, i) => `assets/acciones/capas/capas-${String(i + 1).padStart(2, "0")}.webp`),
        },
      ],
      graficas: [
        "assets/acciones/capas/graficas/capas_flyer-mumi.jpg",
        "assets/acciones/capas/graficas/capas_story-hoy.jpg",
        "assets/acciones/capas/graficas/capas_posteo-3a.jpg",
        "assets/acciones/capas/graficas/capas_posteo-3b.jpg",
        "assets/acciones/capas/graficas/capas_posteo-4.jpg",
        "assets/acciones/capas/graficas/capas_posteo-5.jpg",
        "assets/acciones/capas/graficas/capas_posteo-6.jpg",
      ],
      spots: [
        "assets/acciones/capas/graficas/spot-capas.mp4",
      ],
    },
    {
      slug: "artivismo-por-palestina",
      year: "2025",
      title: "Artivismo por Palestina Colaboración del colectivo Las Selvas",
      sub: "Activación escénica · Varieté Artivismo · Colaboración del colectivo LAS SELVAS",
      tipo: "Intervención",
      lugar: "Plaza Liber Seregni",
      imagen: "assets/acciones/artivismo-por-palestina/portada.jpg",
      descripcion: "Activación escénica realizada en el marco de la Varieté Artivismo por Palestina en la Plaza Liber Seregni. La propuesta explora el potencial del cuerpo como dispositivo poético y político, generando una acción situada que pone en diálogo movimiento, espacio público y compromiso social.",
      ficha: {
        direccion: "Diego Ruella",
        cocreacion: "Punto de Fuga",
        colaboracion: "Las Selvas",
        elenco: ["Agustina Leiva", "Anaclara Oyenart", "Elisa Acosta", "Florencia Mazzucco", "Leticia Moreno", "Stella Peña"],
        produccion: "Cirqueras Feministas",
        vestuario: "Punto de Fuga",
        duracion: "20 minutos",
        registro: "Laura Sosa",
      },
      galeria: [
        {
          seccion: "Registro",
          fotos: Array.from({ length: 8 }, (_, i) => `assets/acciones/artivismo-por-palestina/artivismo-${String(i + 1).padStart(2, "0")}.webp`),
        },
      ],
      graficas: [
        "assets/acciones/artivismo-por-palestina/graficas/Grafica-full.jpg",
        "assets/acciones/artivismo-por-palestina/graficas/POST-1.jpg",
        "assets/acciones/artivismo-por-palestina/graficas/POST-1a.jpg",
        "assets/acciones/artivismo-por-palestina/graficas/POST-1b.jpg",
        "assets/acciones/artivismo-por-palestina/graficas/2A.jpg",
        "assets/acciones/artivismo-por-palestina/graficas/Placas artistas_Artboard 5 copy 16.jpg",
      ],
    },
    {
      slug: "espacio-bahia",
      year: "2025",
      title: "Bahía abierta",
      sub: "Performance",
      tipo: "Performance",
      lugar: "Espacio Bahía",
      imagen: "assets/acciones/espacio-bahia/bahia-hero.webp",
      descripcion: "Performance presentada en Espacio Bahía, lugar de residencia y creación de nuestro colectivo. Durante una jornada de puertas abiertas, compartimos fragmentos de obras y procesos en desarrollo. Entre cuerpos suspendidos, estructuras arquitectónicas en relación con el audiovisual y el uso de software interactivo; la propuesta explora nuevas formas de habitar el espacio, revelando el potencial de la danza aérea con arnés para transformar la percepción del entorno y generar poéticas del movimiento.",
      ficha: {
        direccion: "Diego Ruella",
        cocreacion: "Punto de Fuga",
        elenco: ["Agustina Leiva", "Anaclara Oyenart", "Elisa Acosta", "Florencia Mazzucco", "Leticia Moreno", "Stella Peña"],
        textos: "Florencia Mazzucco",
        produccion: "Punto de Fuga",
        luces: "Diego Ruella",
        visuales: ["Agustina Leiva", "Anaclara Oyenart"],
        disenoGrafico: "Anaclara Oyenart",
        duracion: "30 minutos",
      },
      galeria: [
        {
          seccion: "Registro",
          fotos: Array.from({ length: 10 }, (_, i) => `assets/acciones/espacio-bahia/bahia-${String(i + 1).padStart(2, "0")}.webp`),
        },
      ],
      graficas: [
        "assets/acciones/espacio-bahia/graficas/feed_2--logo.jpg",
        "assets/acciones/espacio-bahia/graficas/feed_2-03.jpg",
        "assets/acciones/espacio-bahia/graficas/feed_2-04.jpg",
        "assets/acciones/espacio-bahia/graficas/feed_2-05.jpg",
        "assets/acciones/espacio-bahia/graficas/feed_2-06.jpg",
      ],
      spots: [
        "assets/acciones/espacio-bahia/graficas/spot-bahia-1.mp4",
      ],
    },
    {
      slug: "29m-pioneras",
      year: "2025",
      title: "29M Pioneras _ Arte, cuerpo y feminismos en el espacio público",
      sub: "Taller gratuito + intervención escénica",
      tipo: "Intervención",
      lugar: "Plaza Las Pioneras · Municipio C",
      imagen: "assets/acciones/29m-pioneras/portada.jpg",
      descripcion: "Proyecto apoyado por el Fondo Municipal de Cultura Comunitaria del Municipio C.<br><br>En el marco de Marzo, mes de la reflexión y visibilización de la igualdad de género y los derechos de las mujeres, desarrollamos una jornada abierta que combinó un taller gratuito de danza aérea y una intervención artística en la Plaza Las Pioneras. A través del movimiento y la ocupación poética del espacio público, la propuesta buscó generar instancias de encuentro, visibilización y reflexión colectiva en torno a los cuerpos, los territorios y las luchas feministas.",
      ficha: {
        direccion: "Diego Ruella",
        elenco: ["Agustina Leiva", "Anaclara Oyenart", "Elisa Acosta", "Florencia Mazzucco", "Leticia Moreno", "Stella Peña"],
        montaje: ["Diego Ruella", "Elisa Acosta", "Leticia Moreno"],
        produccion: "Victoria Beretta",
        disenoGrafico: "Anaclara Oyenart",
        registro: "Ana Micenmacher",
        duracion: ["Taller: 2hs", "Performance: 30 minutos"],
      },
      galeria: [
        {
          seccion: "Taller",
          fotos: Array.from({ length: 22 }, (_, i) => `assets/acciones/29m-pioneras/taller/taller-${String(i + 1).padStart(2, "0")}.webp`),
        },
        {
          seccion: "Intervención",
          fotos: Array.from({ length: 14 }, (_, i) => `assets/acciones/29m-pioneras/intervencion/intervencion-${String(i + 1).padStart(2, "0")}.webp`),
        },
      ],
      graficas: [
        "assets/acciones/29m-pioneras/graficas/flyer_full_info.jpg",
        "assets/acciones/29m-pioneras/graficas/posteo_3.jpg",
        "assets/acciones/29m-pioneras/graficas/posteo_4.jpg",
        "assets/acciones/29m-pioneras/graficas/posteo_5.jpg",
        "assets/acciones/29m-pioneras/graficas/posteo_6.jpg",
      ],
      videos: [
        { label: "Reel", src: "assets/acciones/29m-pioneras/graficas/reel_29M_final-crop.mp4" },
      ],
    },
    {
      slug: "fugas-colectivas-vol-ii",
      year: "2024",
      title: "Fugas Colectivas Vol. II",
      sub: "Obra de danza aérea en arnés",
      tipo: "Obra",
      lugar: "Sala El Picadero",
      mes: "Diciembre",
      imagen: "assets/acciones/fugas-colectivas-vol-ii/portada.jpg",
      frase: "Fugas Colectivas… porque el futuro será colectivo.",
      descripcion: "Fugas Colectivas regresa en una segunda edición en Sala El Picadero, reafirmando y expandiendo la investigación escénica iniciada en su primera versión. La incorporación de nuevas artistas y la exploración de nuevos lenguajes y técnicas enriquecen la propuesta, abriendo otras posibilidades de encuentro, composición y creación colectiva.<br><br>Esta nueva etapa profundiza la investigación sobre el cuerpo suspendido, el espacio, la luz y la poética del movimiento, desarrollando nuevas capas de sentido y complejizando las relaciones entre los cuerpos en escena. A través de imágenes en constante transformación, la obra continúa indagando en las tensiones, resonancias y potencias que emergen de lo colectivo.",
      ficha: {
        direccion: "Diego Ruella",
        cocreacion: "Punto de Fuga",
        elenco: ["Agustina Leiva", "Anaclara Oyenart", "Elisa Acosta", "Florencia Mazzucco", "Leticia Moreno", "Stella Peña", "Victoria Beretta"],
        produccion: "Punto de Fuga",
        luces: "Fernanda Castillo",
        disenoGrafico: "Anaclara Oyenart",
        asistenciaTecnica: "Agustina Rodriguez",
        duracion: "40 minutos",
      },
      galeria: [
        {
          seccion: "Registro",
          fotos: [
            "assets/acciones/fugas-colectivas-vol-ii/A-2.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-3.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-5.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-9.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-19.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-45.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-50.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-56.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-58.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-63.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-67.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-71-2.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-74.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-77.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-105.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-117.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-124.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-130.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-141.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-142.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-146.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-152.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-160.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-168.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-177.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-191.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-196.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-197.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-201.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-207.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-218.jpg",
            "assets/acciones/fugas-colectivas-vol-ii/A-221.jpg",
          ],
        },
      ],
      graficas: [
        "assets/acciones/fugas-colectivas-vol-ii/graficas/fugas_ii_afiche-dic.jpg",
        "assets/acciones/fugas-colectivas-vol-ii/graficas/fugas_ii_posteo-1a.jpg",
        "assets/acciones/fugas-colectivas-vol-ii/graficas/fugas_ii_posteo-1b.jpg",
        "assets/acciones/fugas-colectivas-vol-ii/graficas/fugas_ii_posteo-1c.jpg",
        "assets/acciones/fugas-colectivas-vol-ii/graficas/fugas_ii_posteo-1d.jpg",
        "assets/acciones/fugas-colectivas-vol-ii/graficas/fugas_ii_posteo-3a.jpg",
        "assets/acciones/fugas-colectivas-vol-ii/graficas/fugas_ii_posteo-4a.jpg",
      ],
      spots: [
        "assets/acciones/fugas-colectivas-vol-ii/graficas/fugas_ii_spot-lanzamiento.mp4",
        "assets/acciones/fugas-colectivas-vol-ii/graficas/fugas_ii_spot-lanzamiento-2.mp4",
      ],
    },
    {
      slug: "fugas-colectivas-vol-i",
      year: "2024",
      mes: "Julio",
      title: "Fugas Colectivas Vol. I",
      sub: "Obra de danza aérea en arnés",
      tipo: "Obra",
      lugar: "Sala El Picadero",
      imagen: "assets/acciones/fugas-colectivas-vol-i/portada.jpg",
      frase: "Fugas Colectivas, porque el futuro será colectivo.",
      ficha: {
        direccion: "Diego Ruella",
        cocreacion: "Punto de Fuga",
        elenco: ["Agustina Rodriguez", "Anaclara Oyenart", "Elisa Acosta", "Florencia Mazzucco", "Victoria Berretta"],
        produccion: "Punto de Fuga",
        disenoGrafico: "Anaclara Oyenart",
        luces: "Fernanda Castillo",
        duracion: "40 minutos",
      },
      descripcion: "Es una performance que, desde un lenguaje visual y poético, explora los vínculos y las formas en que nuestros cuerpos son atravesados por fuerzas, discursos y afectos que condicionan nuestra manera de habitar el mundo.<br><br>Interpretada por un elenco de mujeres, la obra se despliega como una composición en movimiento donde luces, trayectorias, péndulos, espirales, puntos y líneas construyen un paisaje dinámico de encuentros y desencuentros. En un espacio finito, los cuerpos se aproximan, se rozan, se desvían, se sostienen y transforman mutuamente, revelando las múltiples posibilidades que emergen de la experiencia colectiva.<br><br>A través de una trama de imágenes en constante transformación, Fugas Colectivas da vida a una pintura en movimiento que invita a reflexionar sobre la interdependencia, la presencia y la construcción de lo común.",
      galeria: [
        {
          seccion: "Registro",
          fotos: Array.from({ length: 42 }, (_, i) => `assets/acciones/fugas-colectivas-vol-i/fugas_i_img-${i + 1}.jpg`),
        },
      ],
      graficas: [
        "assets/acciones/fugas-colectivas-vol-i/graficas/fugas_i_grafica-1.jpg",
        "assets/acciones/fugas-colectivas-vol-i/graficas/fugas_i_grafica-2.jpg",
        "assets/acciones/fugas-colectivas-vol-i/graficas/fugas_i_grafica-3.jpg",
        "assets/acciones/fugas-colectivas-vol-i/graficas/fugas_i_grafica-4.jpg",
        "assets/acciones/fugas-colectivas-vol-i/graficas/fugas_i_grafica-5.jpg",
      ],
      videos: [
        { label: "Reel", src: "assets/acciones/fugas-colectivas-vol-i/graficas/fugas_i_reel-1.mp4" },
      ],
    },
    {
      slug: "apertura-proceso-creativo",
      year: "2023",
      title: "Habitar el Entre _ Apertura de proceso",
      sub: "Muestra abierta",
      tipo: "Ensayo",
      lugar: "La Galponera espacio de circo",
      imagen: "assets/acciones/apertura-proceso-creativo/portada.jpg",
      graficas: [
        "assets/acciones/apertura-proceso-creativo/graficas/flyer.jpg",
      ],
      videos: [
        { label: "Video 1", src: "assets/acciones/apertura-proceso-creativo/apertura_video-1.mp4" },
        { label: "Video 2", src: "assets/acciones/apertura-proceso-creativo/apertura_video-2.mp4" },
        { label: "Video 3", src: "assets/acciones/apertura-proceso-creativo/apertura_video-4.mp4" },
      ],
      ficha: {
        direccion: "Diego Ruella",
        cocreacion: "Punto de Fuga",
        elenco: ["Agustina Rodriguez", "Anaclara Oyenart", "Elisa Acosta", "Florencia Mazzucco", "Victoria Berretta"],
        produccion: "Punto de Fuga",
        luces: "Diego Ruella",
        duracion: "30 minutos",
      },
      descripcion: "Apertura de proceso creativo Fugas Colectivas en el espacio de circo La Galponera.<br><br>Este encuentro con el público permitió compartir fragmentos de la creación en curso, acercando a las y los asistentes a una etapa de trabajo caracterizada por la experimentación, la búsqueda y la construcción colectiva de sentido. El propósito de este encuentro fue generar un espacio de intercambio y escucha que posibilitara recoger impresiones, observaciones y aportes del público, entendiendo el feedback como una herramienta fundamental para enriquecer y fortalecer el proceso creativo. Asimismo, la instancia promovió una dinámica de reflexión y escritura que permitió registrar percepciones y resonancias surgidas a partir de la experiencia compartida. La apertura puso en circulación la obra en su estado más vivo, inacabado y vulnerable, favoreciendo un diálogo directo entre creación y recepción, y reafirmando el valor del encuentro con la comunidad como parte constitutiva del proceso artístico.",
      galeria: [
        {
          seccion: "Registro",
          fotos: Array.from({ length: 19 }, (_, i) => `assets/acciones/apertura-proceso-creativo/apertura_img-${i + 1}.jpg`),
        },
      ],
    },
    {
      slug: "investigacion-visual-luces",
      year: "2022",
      title: "Exploraciones",
      sub: "Proceso de investigación",
      tipo: "Ensayo",
      lugar: "Lugar de ensayo",
      imagen: "assets/acciones/investigacion-visual-luces/portada.jpg",
      descripcion: "Investigación de luces y visuales — exploración del espacio escénico a través de la luz y los recursos visuales como herramientas de creación.",
      galeria: [
        {
          seccion: "Registro",
          fotos: [
            "assets/acciones/investigacion-visual-luces/inv-visual_img-1.jpg",
            "assets/acciones/investigacion-visual-luces/inv-visual_img-2.jpg",
            "assets/acciones/investigacion-visual-luces/inv-visual_img-3.jpg",
            "assets/acciones/investigacion-visual-luces/inv-visual_img-4.jpg",
          ],
        },
      ],
      videos: [
        { label: "Video", src: "assets/acciones/investigacion-visual-luces/inv-visual_video-1.mp4" },
      ],
    },
  ],

  nosInteresa: [
    {
      lead: "Explorar y crear",
      cuerpo: "a través de la danza aérea en diálogo con otros lenguajes, piezas escénicas singulares con identidad propia.",
    },
    {
      lead: "Realizar intervenciones artísticas diversas",
      cuerpo: "y adaptables a múltiples espacios escénicos.",
    },
    {
      lead: "Favorecer encuentros",
      cuerpo: "a través de intervenciones en espacios abiertos a la comunidad, promoviendo el sentido de pertenencia y el uso del espacio público.",
    },
    {
      lead: "Difundir la danza aérea con arneses",
      cuerpo: "destacando su potencial para la investigación y la exploración del trabajo con el cuerpo.",
    },
  ],

  footer: {
    copyright: "© 2018–2026 · Colectivo Punto de Fuga",
  },

  contacto: {
    titulo: "Escribinos.",
    tituloEm: "Programemos.",
    email: "puntodefuga.danzaerea@gmail.com",
    instagram: "puntodefuga.danzaerea",
    instagramUrl: "https://www.instagram.com/puntodefuga.danzaerea/",
    location: "Montevideo · Uruguay",
  },
};
